###################
# Trent Nicholson #
###################
version: "3.0"
services:
  redis:
    image: redis
    networks:
      - app

  flaskapp:
    image: nichtj3/virt-flask-app
    networks:
      - app
    depends_on:
      - redis
    deploy:
      replicas: 3

  nginx:
    image: nichtj3/nginx
    ports:
      - 8080:80
    networks:
      - app
    depends_on:
      - flaskapp
    deploy:
      replicas: 3

networks:
  app:
